version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  rails_tutorial:
    build:
      context: .
      dockerfile: Dockerfile
    command: "rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails_tutorial
    ports:
      - "3000:3000"
    depends_on:
      - db
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"